name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}  # 动态指定操作系统 
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]  # 三大系统矩阵 
        rust: [ stable ]
      fail-fast: false  # 允许单个任务失败不影响其他 

    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@${{ matrix.rust }}  # 动态安装指定版本 

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.8  # 自动处理多平台缓存 

      - name: Run tests
        run: cargo check --locked  # 跨平台通用命令
        if: matrix.os != 'windows-latest'  # 可选条件控制 

      - name: Windows specific setup
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y llvm  # Windows 可能需要额外依赖 
          cargo check --locked
